# Generated by Django 4.1.7 on 2023-03-21 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=75)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['-category_id'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('alt', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
                'ordering': ['-image_id'],
            },
        ),
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('manufacture_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
                'ordering': ['-manufacture_id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=75)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('number_of_available', models.IntegerField()),
                ('main_category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_app.category', verbose_name='Категория')),
                ('main_image_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_app.image', verbose_name='Главная картинка')),
                ('manufacturer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_app.manufacture', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-price', '-product_id', '-number_of_available'],
            },
        ),
        migrations.CreateModel(
            name='Image_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_app.image', verbose_name='Главная картинка')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_app.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фотография товара',
                'verbose_name_plural': 'Фотографии товара',
                'ordering': ['-product_id'],
            },
        ),
        migrations.CreateModel(
            name='Category_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_app.category', verbose_name='Категория')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_app.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Категория товара',
                'verbose_name_plural': 'Категории товара',
                'ordering': ['-product_id', '-category_id'],
            },
        ),
    ]
