# Generated by Django 4.1.7 on 2023-03-21 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category_product',
            options={'ordering': ['-product', '-category'], 'verbose_name': 'Категория товара', 'verbose_name_plural': 'Категории товара'},
        ),
        migrations.AlterModelOptions(
            name='image_product',
            options={'ordering': ['-product'], 'verbose_name': 'Фотография товара', 'verbose_name_plural': 'Фотографии товара'},
        ),
        migrations.RenameField(
            model_name='category_product',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='category_product',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='image_product',
            old_name='image_id',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='image_product',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='main_category_id',
            new_name='main_category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='main_image_id',
            new_name='main_image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='manufacturer_id',
            new_name='manufacturer',
        ),
    ]
